# Generated by Django 5.1.6 on 2025-03-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
